### ISSUE TITLE
Scroll Restoration

### ISSUE THREAD

**Issue by twilson63** [jrs-innovation-center/tcvsn-pwa#28]
When viewing some of the pages the scrolling is not being restored when going to a new page.

https://reacttraining.com/react-router/web/guides/scroll-restoration

Also, you may want the app bar to be fixed at the top

Try position='fixed'

https://material-ui-next.com/api/app-bar/

**Comment by camIAm** [comment]
Application wrapped in a scroll-restoration component. The scrolling problem with about, in memory, and legal appears fixed.
