### ISSUE TITLE
Clean up api docs

### ISSUE THREAD

**Issue by tripott** [jrs-innovation-center/tcvsn-pwa#31]
- clean up the api docs, required fields,  add `cd api` to getting started.

**Comment by twilson63** [comment]
Would be nice to use swagger js-doc to generate api documentation there is also a swagger-markdown module that will generate the json to markdown for the README and docs site.

**Comment by twilson63** [comment]
Here is an example of the swagger generated markdown

https://gist.github.com/twilson63/af4d3a0083771cad5792c684a21b1fd0#resource
