### ISSUE TITLE
Delete Category

### ISSUE THREAD

**Issue by tripott** [jrs-innovation-center/tcvsn-pwa#37]
Provide ability to delete a category when viewing an individual category.  Add delete menu item to the secondary menu.  Provide a confirm dialog.   When deleting a category, set category id to null on all related resource documents.

**Comment by curreythomas** [comment]
team-categories is taking this

**Comment by curreythomas** [comment]
Provided all functionality but decided to deny the deletion of a category if there are any resources that have that category as a categoryId. This will prompt another dialog letting them know how many resources are tied to that category and rejecting their delete.
