### ISSUE TITLE
Filter Resources by selecting a category from category list

### ISSUE THREAD

**Issue by tripott** [jrs-innovation-center/tcvsn-pwa#69]
See related issue #70.  As a veteran, as I am viewing a listing of categories using the **categories list page**, I desire the ability to filter resources by selecting a category item in the list so that I can easily locate resources.  

**Workflow**
- User selects categories from menu drawer.
- User redirected to a listing of category items are displayed
- The user scrolls through category items in the list and selects a category.
- User redirected to the **resources list page** which displays a listing of resource items, _filtered by the selected category_. The resource filter drop down should be set to the selected category.  
- The user selects a different item from the resource filter.  See #70.

**Comment by twilson63** [comment]
@tripott is it ok to show the resources list by category on the category show page?

Seems like there is room at the bottom.

**Comment by twilson63** [comment]
I pushed these changes with #73 - they may need additional love.

**Comment by tripott** [comment]
sounds good to me
