### ISSUE TITLE
Add map on resource show card

### ISSUE THREAD

**Issue by tripott** [jrs-innovation-center/tcvsn-pwa#71]
As a veteran, I wish to view the primary address location for the resource on a map at the top of the resource show card so that I can quickly know the location.  In addition to displaying the map, display the following:  

- Primary address (street, city, state, zip)
- Primary contact phone number

## Implementation Notes

- See [leaflet](http://leafletjs.com/) as a possible mapping library.  
- See [Wireframe](https://github.com/jrs-innovation-center/tcvsn-pwa/blob/master/docs/wireframes.md#resource).  

> Note: Wireframe is old and incorrectly based on an older version of Material UI rather than https://material-ui-next.com/.

**Comment by twilson63** [comment]
I think we can simply add the ability to enter the primary address, then we can use a basic google map embed frame to show the map.

``` html
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3354.0231786467775!2d-79.88227118514469!3d32.79164468096748!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88fe71d14c3b9765%3A0xccb2a0ed01d279fe!2sJRS+Coding+School!5e0!3m2!1sen!2sus!4v1512085749643" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
```

https://developers.google.com/maps/documentation/embed/guide

This should be much easier

**Comment by twilson63** [comment]
Added iframe map, uses title of resource and works pretty well

Posting api key in slack must set env var `REACT_APP_MAP`

Sending PR
