### ISSUE TITLE
(idea): Discussion - Home Page To List a veterans favorite resources

### ISSUE THREAD

**Issue by twilson63** [jrs-innovation-center/tcvsn-pwa#97]
What if the home page was the list of favorited resources by the user, so they could mark a resource as a favorite, we would store the id, name of resource in local storage and retrieve the list when they visit the app again from the save device on the home page.  Then the default view with no favorite resources could be a logo and a note about how to add a favorite resource.

Thoughts???

**Comment by tripott** [comment]
Sounds great.

**Comment by twilson63** [comment]
Where would you put to option or button to add resource as a favorite?
